production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

development:
  secret_key_base: 734e9d58c6ffcc104ee32dda1bff3a87a8abc4670231d0bca087ca05a9195972021c723de2512747119153e36a886a6dc39f6d0ec385986ecb0bc45b92d1385d
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>